name: Release Node.js app

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
              - name: Checkout repository
                uses: actions/checkout@v4

              - name: Set up QEMU
                uses: docker/setup-qemu-action@v3
        
              - name: Install Docker buildx
                uses: docker/setup-buildx-action@v3
        
              - name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            
              - name: Build and push Docker image
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    platforms: linux/amd64,linux/arm64
                    tags: ${{ secrets.DOCKER_USERNAME }}/express-app:latest
            